Chunk {
  id: null,
  ids: null,
  debugId: 1000,
  name: 'main',
  //chunk对应的name
  modules: 
  //表明这个chunk来自于哪些module,此时还没有抽取出来我们的公共模块
   [ NormalModule {
       dependencies: 
        [ ConstDependency { module: null, expression: '', range: [Object], loc: [Object] },
          [length]: 1 ],
      //这个module.block是一个数组，其表示当前这个模块包含的块的个数，如RequireEnsureDependenciesBlock，DependenciesBlock,AsyncDependencyBlock
       blocks: 
        [ RequireEnsureDependenciesBlock {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            chunkName: null,
            chunks: [Object],
            module: [Circular],
            loc: [Object],
            expr: [Object],
            range: [Object],
            chunkNameRange: null,
            parent: [Circular] },
          RequireEnsureDependenciesBlock {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            chunkName: null,
            chunks: [Object],
            module: [Circular],
            loc: [Object],
            expr: [Object],
            range: [Object],
            chunkNameRange: null,
            parent: [Circular] },
          [length]: 2 ],
       variables: [ [length]: 0 ],
       //文件从那个路径获取到的
       context: '/Users/klfang/Desktop/webpack-chunkfilename/src',
       reasons: [ [length]: 0 ],
       debugId: 1000,
       lastId: null,
       id: null,
       portableId: null,
       index: 0,
       index2: 12,
       depth: 0,
       used: true,
       usedExports: true,
       providedExports: true,
       chunks: [ [Circular], [length]: 1 ],
       //这个module所在的chunk是Circular，表示循环引用父级chunk。即当前module所在的chunk就是父级chunk
       warnings: 
        [ { ModuleWarning: 
          /Users/klfang/Desktop/webpack-chunkfilename/src/index.js
            15:31  warning  Strings must use doublequote  quotes
            17:32  warning  Strings must use doublequote  quotes
            18:35  warning  Strings must use doublequote  quotes
            19:23  warning  Strings must use doublequote  quotes
            23:31  warning  Strings must use doublequote  quotes
            25:32  warning  Strings must use doublequote  quotes
            26:29  warning  Strings must use doublequote  quotes
          
          ✖ 7 problems (0 errors, 7 warnings)
          
              at emitWarning (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/webpack/lib/NormalModule.js:88:25)
              at lint (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js:113:9)
              at Object.module.exports (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js:181:3)
              at LOADER_EXECUTION (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
              at runSyncOrAsync (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
              at iterateNormalLoaders (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
              at Array.<anonymous> (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
              at Storage.finished (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
              at /Users/klfang/Desktop/webpack-chunkfilename/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9
              at /Users/klfang/Desktop/webpack-chunkfilename/node_modules/graceful-fs/graceful-fs.js:78:16
              at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
            [stack]: [Getter/Setter],
            name: 'ModuleWarning',
            module: [Circular],
            message: '\n\u001b[4m/Users/klfang/Desktop/webpack-chunkfilename/src/index.js\u001b[24m\n  \u001b[2m15:31\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m17:32\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m18:35\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m19:23\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m23:31\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m25:32\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m26:29\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n\n\u001b[33m\u001b[1m✖ 7 problems (0 errors, 7 warnings)\n\u001b[22m\u001b[39m',
            warning: '\n\u001b[4m/Users/klfang/Desktop/webpack-chunkfilename/src/index.js\u001b[24m\n  \u001b[2m15:31\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m17:32\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m18:35\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m19:23\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m23:31\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m25:32\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m26:29\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n\n\u001b[33m\u001b[1m✖ 7 problems (0 errors, 7 warnings)\n\u001b[22m\u001b[39m',
            origin: null,
            dependencies: null },
          [length]: 1 ],
       dependenciesWarnings: [ [length]: 0 ],
       errors: [ [length]: 0 ],
       dependenciesErrors: [ [length]: 0 ],
       strict: true,
       meta: {},

       request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/babel-loader/lib/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
       //哪些loader对我们的文件进行了处理，如这里就是eslint-loader和babel-loader
       userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
       //userRequest表示这个模块的文件绝对路径
       rawRequest: './src/index.js',
       //加载这个模块时候的相对路径
       parser: 
       //每一个module都有一个parser
        Parser {
          _plugins: 
           { 'evaluate Literal': [Object],
             'evaluate LogicalExpression': [Object],
             'evaluate BinaryExpression': [Object],
             'evaluate UnaryExpression': [Object],
             'evaluate typeof undefined': [Object],
             'evaluate Identifier': [Object],
             'evaluate MemberExpression': [Object],
             'evaluate CallExpression': [Object],
             'evaluate CallExpression .replace': [Object],
             'evaluate CallExpression .substr': [Object],
             'evaluate TemplateLiteral': [Object],
             'evaluate TaggedTemplateExpression': [Object],
             'evaluate CallExpression .substring': [Object],
             'evaluate CallExpression .split': [Object],
             'evaluate ConditionalExpression': [Object],
             'evaluate ArrayExpression': [Object],
             'expression global': [Object],
             'expression process': [Object],
             'expression Buffer': [Object],
             'expression setImmediate': [Object],
             'expression clearImmediate': [Object],
             'call require': [Object],
             program: [Object],
             'evaluate typeof define': [Object],
             'typeof define': [Object],
             'evaluate define': [Object],
             'expression define': [Object],
             'call define': [Object],
             'evaluate typeof exports': [Object],
             'typeof exports': [Object],
             'evaluate exports': [Object],
             'expression exports': [Object],
             'call exports': [Object],
             import: [Object],
             'import specifier': [Object],
             'expression imported var': [Object],
             'expression imported var.*': [Object],
             'call imported var': [Object],
             'hot accept callback': [Object],
             'hot accept without callback': [Object],
             export: [Object],
             'export import': [Object],
             'export expression': [Object],
             'export declaration': [Object],
             'export specifier': [Object],
             'export import specifier': [Object],
             'call require:amd:array': [Object],
             'call require:amd:item': [Object],
             'call require:amd:context': [Object],
             'call define:amd:array': [Object],
             'call define:amd:item': [Object],
             'call define:amd:context': [Object],
             'expression require.amd': [Object],
             'expression define.amd': [Object],
             'expression __webpack_amd_options__': [Object],
             'evaluate typeof define.amd': [Object],
             'evaluate typeof require.amd': [Object],
             'evaluate Identifier define.amd': [Object],
             'evaluate Identifier require.amd': [Object],
             'can-rename define': [Object],
             'rename define': [Object],
             'typeof require': [Object],
             'evaluate typeof require': [Object],
             'typeof require.resolve': [Object],
             'evaluate typeof require.resolve': [Object],
             'typeof require.resolveWeak': [Object],
             'evaluate typeof require.resolveWeak': [Object],
             'evaluate typeof module': [Object],
             'assign require': [Object],
             'can-rename require': [Object],
             'rename require': [Object],
             'typeof module': [Object],
             'expression require.cache': [Object],
             'expression require': [Object],
             'call require:commonjs:item': [Object],
             'call require:commonjs:context': [Object],
             'call require.resolve': [Object],
             'call require.resolveWeak': [Object],
             'call require.resolve(Weak)': [Object],
             'call require.resolve(Weak):item': [Object],
             'call require.resolve(Weak):context': [Object],
             'expression __filename': [Object],
             'evaluate Identifier __filename': [Object],
             'expression __dirname': [Object],
             'evaluate Identifier __dirname': [Object],
             'expression require.main': [Object],
             'expression require.extensions': [Object],
             'expression module.loaded': [Object],
             'expression module.id': [Object],
             'expression module.exports': [Object],
             'evaluate Identifier module.hot': [Object],
             'expression module': [Object],
             'call require.config': [Object],
             'call requirejs.config': [Object],
             'expression require.version': [Object],
             'expression requirejs.onError': [Object],
             'expression __webpack_require__': [Object],
             'evaluate typeof __webpack_require__': [Object],
             'expression __webpack_public_path__': [Object],
             'evaluate typeof __webpack_public_path__': [Object],
             'expression __webpack_modules__': [Object],
             'evaluate typeof __webpack_modules__': [Object],
             'expression __webpack_chunk_load__': [Object],
             'evaluate typeof __webpack_chunk_load__': [Object],
             'expression __non_webpack_require__': [Object],
             'evaluate typeof __non_webpack_require__': [Object],
             'expression __webpack_nonce__': [Object],
             'evaluate typeof __webpack_nonce__': [Object],
             'expression require.onError': [Object],
             'evaluate typeof require.onError': [Object],
             'statement if': [Object],
             'expression ?:': [Object],
             'evaluate Identifier __resourceQuery': [Object],
             'expression __resourceQuery': [Object],
             'call require.include': [Object],
             'evaluate typeof require.include': [Object],
             'typeof require.include': [Object],
             'call require.ensure': [Object],
             'evaluate typeof require.ensure': [Object],
             'typeof require.ensure': [Object],
             'call require.context': [Object],
             'call System.import': [Object],
             'import-call': [Object],
             'typeof System': [Object],
             'evaluate typeof System': [Object],
             'typeof System.import': [Object],
             'evaluate typeof System.import': [Object],
             'evaluate typeof System.set': [Object],
             'expression System.set': [Object],
             'evaluate typeof System.get': [Object],
             'expression System.get': [Object],
             'evaluate typeof System.register': [Object],
             'expression System.register': [Object],
             'expression System': [Object] },
          options: undefined,
          scope: undefined,
          state: undefined },
       resource: '/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
       //这个模块的绝对路径，和module.userRequest相同，是module.rawRequest绝对路径形式
       loaders: 
        [ { loader: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/babel-loader/lib/index.js' },
          { loader: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js' },
          [length]: 2 ],
      //这个module会经过哪些loaders，保存的是loader的绝对路径
       fileDependencies: 
        [ '/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
          [length]: 1 ],
        //来源文件的的数组，包括javascript文件和他引入的其他依赖资源文件如css,image等
       contextDependencies: [ [length]: 0 ],
       error: null,
       _source: 
       //module._source包含的是该模块的具体内容OriginalSource，其中_value表示模块内容，_name和module.request相同
        OriginalSource {
          _value: '\'use strict\';\n\n// var $ = require(\'jquery\');\n\n// $(\'body\').html(\'Hello\');\n\n\n// import $ from \'jquery\';\n// $(\'body\').html(\'Hello\');\n\n\n// import Button from \'./Components/Button\';\n// const button = new Button(\'google.com\');\n//  button.render(\'a\');\n\n//code splitting\nif (document.querySelectorAll(\'a\').length) {\n    require.ensure([], function () {\n        var Button = require(\'./Components/Button\').default;\n        var button = new Button(\'google.com\');\n        button.render(\'a\');\n    });\n}\n\nif (document.querySelectorAll(\'h1\').length) {\n    require.ensure([], function () {\n        var Header = require(\'./Components/Header\').default;\n        new Header().render(\'h1\');\n    });\n}',
          _name: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/babel-loader/lib/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/src/index.js' },
       assets: {},
       built: true,
       _cachedSource: null,
       issuer: null,
       building: undefined,
       buildTimestamp: 1487137260364,//模块编译时间
       cacheable: true //模块是否缓存
     },
     [length]: 1 ],
     //chunk中的模块到这里结束了

  entrypoints: 
   [ Entrypoint { name: 'main', chunks: [ [Circular], [length]: 1 ] },
     [length]: 1 ],
  //该chunk来自于那个入口文件

  chunks: 
  //该chunks表示包含了哪些chunk,main这个chunk包含两个通过require.ensure指定的两个chunk
   [ Chunk {
       id: null,
       ids: null,
       debugId: 1001,
       name: null,
       modules: 
        [ NormalModule {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            context: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components',
            //文件路径folder path
            reasons: [Object],
            debugId: 1004,
            lastId: null,
            id: null,
            portableId: null,
            index: 1,
            index2: 7,
            depth: 1,
            used: true,
            usedExports: true,
            providedExports: true,
            chunks: [Object],
            warnings: [Object],
            dependenciesWarnings: [Object],
            errors: [Object],
            dependenciesErrors: [Object],
            strict: true,
            meta: {},
            request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/babel-loader/lib/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Button.js',
            userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Button.js',
            rawRequest: './Components/Button',
            parser: [Object],
            resource: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Button.js',
            loaders: [Object],
            fileDependencies: [Object],
            contextDependencies: [Object],
            error: null,
            _source: [Object],
            assets: {},
            built: true,
            _cachedSource: null,
            issuer: [Object],
            optional: false,
            building: undefined,
            buildTimestamp: 1487137261098,
            cacheable: true },
          NormalModule {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            context: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/jquery/dist',
            reasons: [Object],
            debugId: 1010,
            lastId: null,
            id: null,
            portableId: null,
            index: 2,
            index2: 0,
            depth: 2,
            used: true,
            usedExports: true,
            providedExports: true,
            chunks: [Object],
            warnings: [Object],
            dependenciesWarnings: [Object],
            errors: [Object],
            dependenciesErrors: [Object],
            strict: false,
            meta: {},
            request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/jquery/dist/jquery.js',
            userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/jquery/dist/jquery.js',
            rawRequest: 'jquery',
            parser: [Object],
            resource: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/jquery/dist/jquery.js',
            loaders: [Object],
            fileDependencies: [Object],
            contextDependencies: [Object],
            error: null,
            _source: [Object],
            assets: {},
            built: true,
            _cachedSource: null,
            issuer: [Object],
            optional: false,
            building: undefined,
            buildTimestamp: 1487137261419,
            cacheable: true },
          NormalModule {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            context: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components',
            reasons: [Object],
            debugId: 1014,
            lastId: null,
            id: null,
            portableId: null,
            index: 3,
            index2: 1,
            depth: 2,
            used: true,
            usedExports: true,
            providedExports: true,
            chunks: [Object],
            warnings: [Object],
            dependenciesWarnings: [Object],
            errors: [Object],
            dependenciesErrors: [Object],
            strict: false,
            meta: {},
            request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/html-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Button.html',
            userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Button.html',
            rawRequest: './Button.html',
            parser: [Object],
            resource: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Button.html',
            loaders: [Object],
            fileDependencies: [Object],
            contextDependencies: [Object],
            error: null,
            _source: [Object],
            assets: {},
            built: true,
            _cachedSource: null,
            issuer: [Object],
            optional: false,
            building: undefined,
            buildTimestamp: 1487137261420,
            cacheable: true },
          NormalModule {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            context: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/mustache',
            reasons: [Object],
            debugId: 1006,
            lastId: null,
            id: null,
            portableId: null,
            index: 4,
            index2: 2,
            depth: 2,
            used: true,
            usedExports: true,
            providedExports: true,
            chunks: [Object],
            warnings: [Object],
            dependenciesWarnings: [Object],
            errors: [Object],
            dependenciesErrors: [Object],
            strict: false,
            meta: {},
            request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/mustache/mustache.js',
            userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/mustache/mustache.js',
            rawRequest: 'mustache',
            parser: [Object],
            resource: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/mustache/mustache.js',
            loaders: [Object],
            fileDependencies: [Object],
            contextDependencies: [Object],
            error: null,
            _source: [Object],
            assets: {},
            built: true,
            _cachedSource: null,
            issuer: [Object],
            optional: false,
            building: undefined,
            buildTimestamp: 1487137261414,
            cacheable: true },
          NormalModule {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            context: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components',
            reasons: [Object],
            debugId: 1018,
            lastId: null,
            id: null,
            portableId: null,
            index: 5,
            index2: 6,
            depth: 2,
            used: true,
            usedExports: true,
            providedExports: true,
            chunks: [Object],
            warnings: [Object],
            dependenciesWarnings: [Object],
            errors: [Object],
            dependenciesErrors: [Object],
            strict: false,
            meta: {},
            request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/style-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/css-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/sass-loader/lib/loader.js!/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Button.scss',
            userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Button.scss',
            rawRequest: './Button.scss',
            parser: [Object],
            resource: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Button.scss',
            loaders: [Object],
            fileDependencies: [Object],
            contextDependencies: [Object],
            error: null,
            _source: [Object],
            assets: {},
            built: true,
            _cachedSource: null,
            issuer: [Object],
            optional: false,
            building: undefined,
            buildTimestamp: 1487137261638,
            cacheable: true },
          NormalModule {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            context: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components',
            reasons: [Object],
            debugId: 1022,
            lastId: null,
            id: null,
            portableId: null,
            index: 6,
            index2: 4,
            depth: 3,
            used: true,
            usedExports: true,
            providedExports: true,
            chunks: [Object],
            warnings: [Object],
            dependenciesWarnings: [Object],
            errors: [Object],
            dependenciesErrors: [Object],
            strict: false,
            meta: {},
            request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/css-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/sass-loader/lib/loader.js!/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Button.scss',
            userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/css-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/sass-loader/lib/loader.js!/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Button.scss',
            rawRequest: '!!./../../node_modules/css-loader/index.js!./../../node_modules/sass-loader/lib/loader.js!./Button.scss',
            parser: [Object],
            resource: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Button.scss',
            loaders: [Object],
            fileDependencies: [Object],
            contextDependencies: [Object],
            error: null,
            _source: [Object],
            assets: {},
            built: true,
            _cachedSource: null,
            issuer: [Object],
            optional: false,
            building: undefined,
            buildTimestamp: 1487137261648,
            cacheable: true },
          NormalModule {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            context: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/style-loader',
            reasons: [Object],
            debugId: 1024,
            lastId: null,
            id: null,
            portableId: null,
            index: 8,
            index2: 5,
            depth: 3,
            used: true,
            usedExports: true,
            providedExports: true,
            chunks: [Object],
            warnings: [Object],
            dependenciesWarnings: [Object],
            errors: [Object],
            dependenciesErrors: [Object],
            strict: false,
            meta: {},
            request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/style-loader/addStyles.js',
            userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/style-loader/addStyles.js',
            rawRequest: '!./../../node_modules/style-loader/addStyles.js',
            parser: [Object],
            resource: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/style-loader/addStyles.js',
            loaders: [Object],
            fileDependencies: [Object],
            contextDependencies: [Object],
            error: null,
            _source: [Object],
            assets: {},
            built: true,
            _cachedSource: null,
            issuer: [Object],
            optional: false,
            building: undefined,
            buildTimestamp: 1487137262047,
            cacheable: true },
          NormalModule {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            context: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/css-loader/lib',
            reasons: [Object],
            debugId: 1026,
            lastId: null,
            id: null,
            portableId: null,
            index: 7,
            index2: 3,
            depth: 4,
            used: true,
            usedExports: true,
            providedExports: true,
            chunks: [Object],
            warnings: [Object],
            dependenciesWarnings: [Object],
            errors: [Object],
            dependenciesErrors: [Object],
            strict: false,
            meta: {},
            request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/css-loader/lib/css-base.js',
            userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/css-loader/lib/css-base.js',
            rawRequest: './../../node_modules/css-loader/lib/css-base.js',
            parser: [Object],
            resource: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/css-loader/lib/css-base.js',
            loaders: [Object],
            fileDependencies: [Object],
            contextDependencies: [Object],
            error: null,
            _source: [Object],
            assets: {},
            built: true,
            _cachedSource: null,
            issuer: [Object],
            optional: false,
            building: undefined,
            buildTimestamp: 1487137262287,
            cacheable: true },
          [length]: 8 ],
       entrypoints: [ [length]: 0 ],
       chunks: [ [length]: 0 ],
       parents: [ [Circular], [length]: 1 ],
       blocks: 
        [ RequireEnsureDependenciesBlock {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            chunkName: null,
            chunks: [Object],
            module: [Object],
            loc: [Object],
            expr: [Object],
            range: [Object],
            chunkNameRange: null,
            parent: [Object] },
          [length]: 1 ],
       origins: [ { module: [Object], loc: [Object], name: null }, [length]: 1 ],
       files: [ [length]: 0 ],
       rendered: false,
       _removeAndDo: 
        { [Function: removeAndDo]
          [length]: 3,
          [name]: 'removeAndDo',
          [arguments]: null,
          [caller]: null,
          [prototype]: removeAndDo { [constructor]: [Circular] } },
       addChunk: { [Function: createAdderCallback] [length]: 1, [name]: 'createAdderCallback' },
       addParent: { [Function: createAdderCallback] [length]: 1, [name]: 'createAdderCallback' } },
     Chunk {
       id: null,
       ids: null,
       debugId: 1002,
       name: null,
       modules: 
        [ NormalModule {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            context: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components',
            reasons: [Object],
            debugId: 1005,
            lastId: null,
            id: null,
            portableId: null,
            index: 9,
            index2: 11,
            depth: 1,
            used: true,
            usedExports: true,
            providedExports: true,
            chunks: [Object],
            warnings: [Object],
            dependenciesWarnings: [Object],
            errors: [Object],
            dependenciesErrors: [Object],
            strict: true,
            meta: {},
            request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/babel-loader/lib/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Header.js',
            userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Header.js',
            rawRequest: './Components/Header',
            parser: [Object],
            resource: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Header.js',
            loaders: [Object],
            fileDependencies: [Object],
            contextDependencies: [Object],
            error: null,
            _source: [Object],
            assets: {},
            built: true,
            _cachedSource: null,
            issuer: [Object],
            optional: false,
            building: undefined,
            buildTimestamp: 1487137261098,
            cacheable: true },
          NormalModule {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            context: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/jquery/dist',
            reasons: [Object],
            debugId: 1010,
            lastId: null,
            id: null,
            portableId: null,
            index: 2,
            index2: 0,
            depth: 2,
            used: true,
            usedExports: true,
            providedExports: true,
            chunks: [Object],
            warnings: [Object],
            dependenciesWarnings: [Object],
            errors: [Object],
            dependenciesErrors: [Object],
            strict: false,
            meta: {},
            request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/jquery/dist/jquery.js',
            userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/jquery/dist/jquery.js',
            rawRequest: 'jquery',
            parser: [Object],
            resource: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/jquery/dist/jquery.js',
            loaders: [Object],
            fileDependencies: [Object],
            contextDependencies: [Object],
            error: null,
            _source: [Object],
            assets: {},
            built: true,
            _cachedSource: null,
            issuer: [Object],
            optional: false,
            building: undefined,
            buildTimestamp: 1487137261419,
            cacheable: true },
          NormalModule {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            context: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/mustache',
            reasons: [Object],
            debugId: 1006,
            lastId: null,
            id: null,
            portableId: null,
            index: 4,
            index2: 2,
            depth: 2,
            used: true,
            usedExports: true,
            providedExports: true,
            chunks: [Object],
            warnings: [Object],
            dependenciesWarnings: [Object],
            errors: [Object],
            dependenciesErrors: [Object],
            strict: false,
            meta: {},
            request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/mustache/mustache.js',
            userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/mustache/mustache.js',
            rawRequest: 'mustache',
            parser: [Object],
            resource: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/mustache/mustache.js',
            loaders: [Object],
            fileDependencies: [Object],
            contextDependencies: [Object],
            error: null,
            _source: [Object],
            assets: {},
            built: true,
            _cachedSource: null,
            issuer: [Object],
            optional: false,
            building: undefined,
            buildTimestamp: 1487137261414,
            cacheable: true },
          NormalModule {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            context: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components',
            reasons: [Object],
            debugId: 1016,
            lastId: null,
            id: null,
            portableId: null,
            index: 10,
            index2: 8,
            depth: 2,
            used: true,
            usedExports: true,
            providedExports: true,
            chunks: [Object],
            warnings: [Object],
            dependenciesWarnings: [Object],
            errors: [Object],
            dependenciesErrors: [Object],
            strict: false,
            meta: {},
            request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/html-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Header.html',
            userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Header.html',
            rawRequest: './Header.html',
            parser: [Object],
            resource: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Header.html',
            loaders: [Object],
            fileDependencies: [Object],
            contextDependencies: [Object],
            error: null,
            _source: [Object],
            assets: {},
            built: true,
            _cachedSource: null,
            issuer: [Object],
            optional: false,
            building: undefined,
            buildTimestamp: 1487137261635,
            cacheable: true },
          NormalModule {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            context: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components',
            reasons: [Object],
            debugId: 1020,
            lastId: null,
            id: null,
            portableId: null,
            index: 11,
            index2: 10,
            depth: 2,
            used: true,
            usedExports: true,
            providedExports: true,
            chunks: [Object],
            warnings: [Object],
            dependenciesWarnings: [Object],
            errors: [Object],
            dependenciesErrors: [Object],
            strict: false,
            meta: {},
            request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/style-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/css-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/sass-loader/lib/loader.js!/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Header.scss',
            userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Header.scss',
            rawRequest: './Header.scss',
            parser: [Object],
            resource: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Header.scss',
            loaders: [Object],
            fileDependencies: [Object],
            contextDependencies: [Object],
            error: null,
            _source: [Object],
            assets: {},
            built: true,
            _cachedSource: null,
            issuer: [Object],
            optional: false,
            building: undefined,
            buildTimestamp: 1487137261643,
            cacheable: true },
          NormalModule {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            context: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components',
            reasons: [Object],
            debugId: 1023,
            lastId: null,
            id: null,
            portableId: null,
            index: 12,
            index2: 9,
            depth: 3,
            used: true,
            usedExports: true,
            providedExports: true,
            chunks: [Object],
            warnings: [Object],
            dependenciesWarnings: [Object],
            errors: [Object],
            dependenciesErrors: [Object],
            strict: false,
            meta: {},
            request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/css-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/sass-loader/lib/loader.js!/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Header.scss',
            userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/css-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/sass-loader/lib/loader.js!/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Header.scss',
            rawRequest: '!!./../../node_modules/css-loader/index.js!./../../node_modules/sass-loader/lib/loader.js!./Header.scss',
            parser: [Object],
            resource: '/Users/klfang/Desktop/webpack-chunkfilename/src/Components/Header.scss',
            loaders: [Object],
            fileDependencies: [Object],
            contextDependencies: [Object],
            error: null,
            _source: [Object],
            assets: {},
            built: true,
            _cachedSource: null,
            issuer: [Object],
            optional: false,
            building: undefined,
            buildTimestamp: 1487137262019,
            cacheable: true },
          NormalModule {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            context: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/style-loader',
            reasons: [Object],
            debugId: 1024,
            lastId: null,
            id: null,
            portableId: null,
            index: 8,
            index2: 5,
            depth: 3,
            used: true,
            usedExports: true,
            providedExports: true,
            chunks: [Object],
            warnings: [Object],
            dependenciesWarnings: [Object],
            errors: [Object],
            dependenciesErrors: [Object],
            strict: false,
            meta: {},
            request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/style-loader/addStyles.js',
            userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/style-loader/addStyles.js',
            rawRequest: '!./../../node_modules/style-loader/addStyles.js',
            parser: [Object],
            resource: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/style-loader/addStyles.js',
            loaders: [Object],
            fileDependencies: [Object],
            contextDependencies: [Object],
            error: null,
            _source: [Object],
            assets: {},
            built: true,
            _cachedSource: null,
            issuer: [Object],
            optional: false,
            building: undefined,
            buildTimestamp: 1487137262047,
            cacheable: true },
          NormalModule {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            context: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/css-loader/lib',
            reasons: [Object],
            debugId: 1026,
            lastId: null,
            id: null,
            portableId: null,
            index: 7,
            index2: 3,
            depth: 4,
            used: true,
            usedExports: true,
            providedExports: true,
            chunks: [Object],
            warnings: [Object],
            dependenciesWarnings: [Object],
            errors: [Object],
            dependenciesErrors: [Object],
            strict: false,
            meta: {},
            request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/css-loader/lib/css-base.js',
            userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/css-loader/lib/css-base.js',
            rawRequest: './../../node_modules/css-loader/lib/css-base.js',
            parser: [Object],
            resource: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/css-loader/lib/css-base.js',
            loaders: [Object],
            fileDependencies: [Object],
            contextDependencies: [Object],
            error: null,
            _source: [Object],
            assets: {},
            built: true,
            _cachedSource: null,
            issuer: [Object],
            optional: false,
            building: undefined,
            buildTimestamp: 1487137262287,
            cacheable: true },
          [length]: 8 ],
       entrypoints: [ [length]: 0 ],
       chunks: [ [length]: 0 ],
       parents: [ [Circular], [length]: 1 ],
       blocks: 
        [ RequireEnsureDependenciesBlock {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            chunkName: null,
            chunks: [Object],
            module: [Object],
            loc: [Object],
            expr: [Object],
            range: [Object],
            chunkNameRange: null,
            parent: [Object] },
          [length]: 1 ],
       origins: [ { module: [Object], loc: [Object], name: null }, [length]: 1 ],
       files: [ [length]: 0 ],
       rendered: false,
       _removeAndDo: 
        { [Function: removeAndDo]
          [length]: 3,
          [name]: 'removeAndDo',
          [arguments]: null,
          [caller]: null,
          [prototype]: removeAndDo { [constructor]: [Circular] } },
       addChunk: { [Function: createAdderCallback] [length]: 1, [name]: 'createAdderCallback' },
       addParent: { [Function: createAdderCallback] [length]: 1, [name]: 'createAdderCallback' } },
     [length]: 2 ],
    //chunks结束
  parents: [ [length]: 0 ],
  //父级chunk
  blocks: [ [length]: 0 ],
  //当前chunk包含的block的个数而不是当前module
  origins: 
   [ { module: 
        NormalModule {
          dependencies: [ [Object], [length]: 1 ],
          blocks: [ [Object], [Object], [length]: 2 ],
          variables: [ [length]: 0 ],
          context: '/Users/klfang/Desktop/webpack-chunkfilename/src',
          reasons: [ [length]: 0 ],
          debugId: 1000,
          lastId: null,
          id: null,
          portableId: null,
          index: 0,
          index2: 12,
          depth: 0,
          used: true,
          usedExports: true,
          providedExports: true,
          chunks: [ [Circular], [length]: 1 ],
          warnings: [ [Object], [length]: 1 ],
          dependenciesWarnings: [ [length]: 0 ],
          errors: [ [length]: 0 ],
          dependenciesErrors: [ [length]: 0 ],
          strict: true,
          meta: {},
          request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/babel-loader/lib/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
          userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
          rawRequest: './src/index.js',
          parser: 
           Parser {
             _plugins: [Object],
             options: undefined,
             scope: undefined,
             state: undefined },
          resource: '/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
          loaders: [ [Object], [Object], [length]: 2 ],
          fileDependencies: 
           [ '/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
             [length]: 1 ],
          contextDependencies: [ [length]: 0 ],
          error: null,
          _source: 
           OriginalSource {
             _value: '\'use strict\';\n\n// var $ = require(\'jquery\');\n\n// $(\'body\').html(\'Hello\');\n\n\n// import $ from \'jquery\';\n// $(\'body\').html(\'Hello\');\n\n\n// import Button from \'./Components/Button\';\n// const button = new Button(\'google.com\');\n//  button.render(\'a\');\n\n//code splitting\nif (document.querySelectorAll(\'a\').length) {\n    require.ensure([], function () {\n        var Button = require(\'./Components/Button\').default;\n        var button = new Button(\'google.com\');\n        button.render(\'a\');\n    });\n}\n\nif (document.querySelectorAll(\'h1\').length) {\n    require.ensure([], function () {\n        var Header = require(\'./Components/Header\').default;\n        new Header().render(\'h1\');\n    });\n}',
             _name: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/babel-loader/lib/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/src/index.js' },
          assets: {},
          built: true,
          _cachedSource: null,
          issuer: null,
          building: undefined,
          buildTimestamp: 1487137260364,
          cacheable: true },
       loc: undefined,
       name: 'main' },
     [length]: 1 ],
  files: [ [length]: 0 ],
  // An array of output filenames generated by the chunk. 
  //You may access these asset sources from the compilation.assets table.
  rendered: false,
  _removeAndDo: 
   { [Function: removeAndDo]
     [length]: 3,
     [name]: 'removeAndDo',
     [arguments]: null,
     [caller]: null,
     [prototype]: removeAndDo { [constructor]: [Circular] } },
  addChunk: { [Function: createAdderCallback] [length]: 1, [name]: 'createAdderCallback' },
  addParent: { [Function: createAdderCallback] [length]: 1, [name]: 'createAdderCallback' },
  //入口模块
  entryModule: 
   NormalModule {
     dependencies: 
      [ ConstDependency {
          module: null,
          expression: '',
          range: [ 0, 13, [length]: 2 ],
          loc: SourceLocation { start: [Object], end: [Object] } },
        [length]: 1 ],
     blocks: 
      [ RequireEnsureDependenciesBlock {
          dependencies: [ [Object], [Object], [Object], [length]: 3 ],
          blocks: [ [length]: 0 ],
          variables: [ [length]: 0 ],
          chunkName: null,
          chunks: [ [Object], [length]: 1 ],
          module: [Circular],
          loc: SourceLocation { start: [Object], end: [Object] },
          expr: 
           Node {
             type: 'CallExpression',
             start: 313,
             end: 488,
             loc: [Object],
             range: [Object],
             callee: [Object],
             arguments: [Object] },
          range: [ 345, 486, [length]: 2 ],
          chunkNameRange: null,
          parent: [Circular] },
        RequireEnsureDependenciesBlock {
          dependencies: [ [Object], [Object], [Object], [length]: 3 ],
          blocks: [ [length]: 0 ],
          variables: [ [length]: 0 ],
          chunkName: null,
          chunks: [ [Object], [length]: 1 ],
          module: [Circular],
          loc: SourceLocation { start: [Object], end: [Object] },
          expr: 
           Node {
             type: 'CallExpression',
             start: 543,
             end: 678,
             loc: [Object],
             range: [Object],
             callee: [Object],
             arguments: [Object] },
          range: [ 575, 676, [length]: 2 ],
          chunkNameRange: null,
          parent: [Circular] },
        [length]: 2 ],
     variables: [ [length]: 0 ],
     context: '/Users/klfang/Desktop/webpack-chunkfilename/src',
     reasons: [ [length]: 0 ],
     debugId: 1000,
     lastId: null,
     id: null,
     portableId: null,
     index: 0,
     index2: 12,
     depth: 0,
     used: true,
     usedExports: true,
     providedExports: true,
     chunks: [ [Circular], [length]: 1 ],
     warnings: 
      [ { ModuleWarning: 
        /Users/klfang/Desktop/webpack-chunkfilename/src/index.js
          15:31  warning  Strings must use doublequote  quotes
          17:32  warning  Strings must use doublequote  quotes
          18:35  warning  Strings must use doublequote  quotes
          19:23  warning  Strings must use doublequote  quotes
          23:31  warning  Strings must use doublequote  quotes
          25:32  warning  Strings must use doublequote  quotes
          26:29  warning  Strings must use doublequote  quotes
        
        ✖ 7 problems (0 errors, 7 warnings)
        
            at emitWarning (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/webpack/lib/NormalModule.js:88:25)
            at lint (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js:113:9)
            at Object.module.exports (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js:181:3)
            at LOADER_EXECUTION (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
            at runSyncOrAsync (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
            at iterateNormalLoaders (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
            at Array.<anonymous> (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
            at Storage.finished (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
            at /Users/klfang/Desktop/webpack-chunkfilename/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9
            at /Users/klfang/Desktop/webpack-chunkfilename/node_modules/graceful-fs/graceful-fs.js:78:16
            at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
          [stack]: [Getter/Setter],
          name: 'ModuleWarning',
          module: [Circular],
          message: '\n\u001b[4m/Users/klfang/Desktop/webpack-chunkfilename/src/index.js\u001b[24m\n  \u001b[2m15:31\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m17:32\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m18:35\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m19:23\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m23:31\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m25:32\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m26:29\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n\n\u001b[33m\u001b[1m✖ 7 problems (0 errors, 7 warnings)\n\u001b[22m\u001b[39m',
          warning: '\n\u001b[4m/Users/klfang/Desktop/webpack-chunkfilename/src/index.js\u001b[24m\n  \u001b[2m15:31\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m17:32\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m18:35\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m19:23\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m23:31\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m25:32\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m26:29\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n\n\u001b[33m\u001b[1m✖ 7 problems (0 errors, 7 warnings)\n\u001b[22m\u001b[39m',
          origin: null,
          dependencies: null },
        [length]: 1 ],
     dependenciesWarnings: [ [length]: 0 ],
     errors: [ [length]: 0 ],
     dependenciesErrors: [ [length]: 0 ],
     strict: true,
     meta: {},
     request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/babel-loader/lib/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
     userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
     rawRequest: './src/index.js',
     parser: 
      Parser {
        _plugins: 
         { 'evaluate Literal': [ [Object], [length]: 1 ],
           'evaluate LogicalExpression': [ [Object], [length]: 1 ],
           'evaluate BinaryExpression': [ [Object], [length]: 1 ],
           'evaluate UnaryExpression': [ [Object], [length]: 1 ],
           'evaluate typeof undefined': [ [Object], [length]: 1 ],
           'evaluate Identifier': [ [Object], [length]: 1 ],
           'evaluate MemberExpression': [ [Object], [length]: 1 ],
           'evaluate CallExpression': [ [Object], [length]: 1 ],
           'evaluate CallExpression .replace': [ [Object], [length]: 1 ],
           'evaluate CallExpression .substr': [ [Object], [length]: 1 ],
           'evaluate TemplateLiteral': [ [Object], [Object], [length]: 2 ],
           'evaluate TaggedTemplateExpression': [ [Object], [Object], [length]: 2 ],
           'evaluate CallExpression .substring': [ [Object], [length]: 1 ],
           'evaluate CallExpression .split': [ [Object], [length]: 1 ],
           'evaluate ConditionalExpression': [ [Object], [length]: 1 ],
           'evaluate ArrayExpression': [ [Object], [length]: 1 ],
           'expression global': [ [Object], [length]: 1 ],
           'expression process': [ [Object], [length]: 1 ],
           'expression Buffer': [ [Object], [length]: 1 ],
           'expression setImmediate': [ [Object], [length]: 1 ],
           'expression clearImmediate': [ [Object], [length]: 1 ],
           'call require': [ [Object], [Object], [Object], [length]: 3 ],
           program: [ [Object], [Object], [length]: 2 ],
           'evaluate typeof define': [ [Object], [Object], [length]: 2 ],
           'typeof define': [ [Object], [Object], [length]: 2 ],
           'evaluate define': [ [Object], [length]: 1 ],
           'expression define': [ [Object], [Object], [length]: 2 ],
           'call define': [ [Object], [Object], [length]: 2 ],
           'evaluate typeof exports': [ [Object], [Object], [length]: 2 ],
           'typeof exports': [ [Object], [length]: 1 ],
           'evaluate exports': [ [Object], [length]: 1 ],
           'expression exports': [ [Object], [length]: 1 ],
           'call exports': [ [Object], [length]: 1 ],
           import: [ [Object], [length]: 1 ],
           'import specifier': [ [Object], [length]: 1 ],
           'expression imported var': [ [Object], [length]: 1 ],
           'expression imported var.*': [ [Object], [length]: 1 ],
           'call imported var': [ [Object], [length]: 1 ],
           'hot accept callback': [ [Object], [length]: 1 ],
           'hot accept without callback': [ [Object], [length]: 1 ],
           export: [ [Object], [length]: 1 ],
           'export import': [ [Object], [length]: 1 ],
           'export expression': [ [Object], [length]: 1 ],
           'export declaration': [ [Object], [length]: 1 ],
           'export specifier': [ [Object], [length]: 1 ],
           'export import specifier': [ [Object], [length]: 1 ],
           'call require:amd:array': [ [Object], [length]: 1 ],
           'call require:amd:item': [ [Object], [length]: 1 ],
           'call require:amd:context': [ [Object], [length]: 1 ],
           'call define:amd:array': [ [Object], [length]: 1 ],
           'call define:amd:item': [ [Object], [length]: 1 ],
           'call define:amd:context': [ [Object], [length]: 1 ],
           'expression require.amd': [ [Object], [length]: 1 ],
           'expression define.amd': [ [Object], [length]: 1 ],
           'expression __webpack_amd_options__': [ [Object], [length]: 1 ],
           'evaluate typeof define.amd': [ [Object], [length]: 1 ],
           'evaluate typeof require.amd': [ [Object], [length]: 1 ],
           'evaluate Identifier define.amd': [ [Object], [length]: 1 ],
           'evaluate Identifier require.amd': [ [Object], [length]: 1 ],
           'can-rename define': [ [Object], [length]: 1 ],
           'rename define': [ [Object], [length]: 1 ],
           'typeof require': [ [Object], [Object], [length]: 2 ],
           'evaluate typeof require': [ [Object], [Object], [length]: 2 ],
           'typeof require.resolve': [ [Object], [length]: 1 ],
           'evaluate typeof require.resolve': [ [Object], [length]: 1 ],
           'typeof require.resolveWeak': [ [Object], [length]: 1 ],
           'evaluate typeof require.resolveWeak': [ [Object], [length]: 1 ],
           'evaluate typeof module': [ [Object], [length]: 1 ],
           'assign require': [ [Object], [length]: 1 ],
           'can-rename require': [ [Object], [length]: 1 ],
           'rename require': [ [Object], [length]: 1 ],
           'typeof module': [ [Object], [length]: 1 ],
           'expression require.cache': [ [Object], [length]: 1 ],
           'expression require': [ [Object], [length]: 1 ],
           'call require:commonjs:item': [ [Object], [length]: 1 ],
           'call require:commonjs:context': [ [Object], [length]: 1 ],
           'call require.resolve': [ [Object], [length]: 1 ],
           'call require.resolveWeak': [ [Object], [length]: 1 ],
           'call require.resolve(Weak)': [ [Object], [length]: 1 ],
           'call require.resolve(Weak):item': [ [Object], [length]: 1 ],
           'call require.resolve(Weak):context': [ [Object], [length]: 1 ],
           'expression __filename': [ [Object], [length]: 1 ],
           'evaluate Identifier __filename': [ [Object], [length]: 1 ],
           'expression __dirname': [ [Object], [length]: 1 ],
           'evaluate Identifier __dirname': [ [Object], [length]: 1 ],
           'expression require.main': [ [Object], [length]: 1 ],
           'expression require.extensions': [ [Object], [length]: 1 ],
           'expression module.loaded': [ [Object], [length]: 1 ],
           'expression module.id': [ [Object], [length]: 1 ],
           'expression module.exports': [ [Object], [length]: 1 ],
           'evaluate Identifier module.hot': [ [Object], [length]: 1 ],
           'expression module': [ [Object], [length]: 1 ],
           'call require.config': [ [Object], [length]: 1 ],
           'call requirejs.config': [ [Object], [length]: 1 ],
           'expression require.version': [ [Object], [length]: 1 ],
           'expression requirejs.onError': [ [Object], [length]: 1 ],
           'expression __webpack_require__': [ [Object], [length]: 1 ],
           'evaluate typeof __webpack_require__': [ [Object], [length]: 1 ],
           'expression __webpack_public_path__': [ [Object], [length]: 1 ],
           'evaluate typeof __webpack_public_path__': [ [Object], [length]: 1 ],
           'expression __webpack_modules__': [ [Object], [length]: 1 ],
           'evaluate typeof __webpack_modules__': [ [Object], [length]: 1 ],
           'expression __webpack_chunk_load__': [ [Object], [length]: 1 ],
           'evaluate typeof __webpack_chunk_load__': [ [Object], [length]: 1 ],
           'expression __non_webpack_require__': [ [Object], [length]: 1 ],
           'evaluate typeof __non_webpack_require__': [ [Object], [length]: 1 ],
           'expression __webpack_nonce__': [ [Object], [length]: 1 ],
           'evaluate typeof __webpack_nonce__': [ [Object], [length]: 1 ],
           'expression require.onError': [ [Object], [length]: 1 ],
           'evaluate typeof require.onError': [ [Object], [length]: 1 ],
           'statement if': [ [Object], [length]: 1 ],
           'expression ?:': [ [Object], [length]: 1 ],
           'evaluate Identifier __resourceQuery': [ [Object], [length]: 1 ],
           'expression __resourceQuery': [ [Object], [length]: 1 ],
           'call require.include': [ [Object], [length]: 1 ],
           'evaluate typeof require.include': [ [Object], [length]: 1 ],
           'typeof require.include': [ [Object], [length]: 1 ],
           'call require.ensure': [ [Object], [length]: 1 ],
           'evaluate typeof require.ensure': [ [Object], [length]: 1 ],
           'typeof require.ensure': [ [Object], [length]: 1 ],
           'call require.context': [ [Object], [length]: 1 ],
           'call System.import': [ [Object], [length]: 1 ],
           'import-call': [ [Object], [length]: 1 ],
           'typeof System': [ [Object], [length]: 1 ],
           'evaluate typeof System': [ [Object], [length]: 1 ],
           'typeof System.import': [ [Object], [length]: 1 ],
           'evaluate typeof System.import': [ [Object], [length]: 1 ],
           'evaluate typeof System.set': [ [Object], [length]: 1 ],
           'expression System.set': [ [Object], [length]: 1 ],
           'evaluate typeof System.get': [ [Object], [length]: 1 ],
           'expression System.get': [ [Object], [length]: 1 ],
           'evaluate typeof System.register': [ [Object], [length]: 1 ],
           'expression System.register': [ [Object], [length]: 1 ],
           'expression System': [ [Object], [length]: 1 ] },
        options: undefined,
        scope: undefined,
        state: undefined },
     resource: '/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
     loaders: 
      [ { loader: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/babel-loader/lib/index.js' },
        { loader: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js' },
        [length]: 2 ],
     fileDependencies: 
      [ '/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
        [length]: 1 ],
     contextDependencies: [ [length]: 0 ],
     error: null,
     _source: 
      OriginalSource {
        _value: '\'use strict\';\n\n// var $ = require(\'jquery\');\n\n// $(\'body\').html(\'Hello\');\n\n\n// import $ from \'jquery\';\n// $(\'body\').html(\'Hello\');\n\n\n// import Button from \'./Components/Button\';\n// const button = new Button(\'google.com\');\n//  button.render(\'a\');\n\n//code splitting\nif (document.querySelectorAll(\'a\').length) {\n    require.ensure([], function () {\n        var Button = require(\'./Components/Button\').default;\n        var button = new Button(\'google.com\');\n        button.render(\'a\');\n    });\n}\n\nif (document.querySelectorAll(\'h1\').length) {\n    require.ensure([], function () {\n        var Header = require(\'./Components/Header\').default;\n        new Header().render(\'h1\');\n    });\n}',
        _name: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/babel-loader/lib/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/src/index.js' },
     assets: {},
     built: true,
     _cachedSource: null,
     issuer: null,
     building: undefined,
     buildTimestamp: 1487137260364,
     cacheable: true } }