[ Chunk {
    id: null,
    ids: null,
    debugId: 1000,
    name: 'main',
    modules: 
     [ NormalModule {
         dependencies: [ [Object], [length]: 1 ],
         blocks: [ [Object], [Object], [length]: 2 ],
         variables: [ [length]: 0 ],
         context: '/Users/klfang/Desktop/webpack-chunkfilename/src',
         reasons: [ [length]: 0 ],
         debugId: 1000,
         lastId: null,
         id: null,
         portableId: null,
         index: 0,
         index2: 12,
         depth: 0,
         used: true,
         usedExports: true,
         providedExports: true,
         chunks: [ [Circular], [length]: 1 ],
         warnings: [ [Object], [length]: 1 ],
         dependenciesWarnings: [ [length]: 0 ],
         errors: [ [length]: 0 ],
         dependenciesErrors: [ [length]: 0 ],
         strict: true,
         meta: {},
         request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/babel-loader/lib/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
         userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
         rawRequest: './src/index.js',
         parser: 
          Parser {
            _plugins: [Object],
            options: undefined,
            scope: undefined,
            state: undefined },
         resource: '/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
         loaders: [ [Object], [Object], [length]: 2 ],
         fileDependencies: 
          [ '/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
            [length]: 1 ],
         contextDependencies: [ [length]: 0 ],
         error: null,
         _source: 
          OriginalSource {
            _value: '\'use strict\';\n\n// var $ = require(\'jquery\');\n\n// $(\'body\').html(\'Hello\');\n\n\n// import $ from \'jquery\';\n// $(\'body\').html(\'Hello\');\n\n\n// import Button from \'./Components/Button\';\n// const button = new Button(\'google.com\');\n//  button.render(\'a\');\n\n//code splitting\nif (document.querySelectorAll(\'a\').length) {\n    require.ensure([], function () {\n        var Button = require(\'./Components/Button\').default;\n        var button = new Button(\'google.com\');\n        button.render(\'a\');\n    });\n}\n\nif (document.querySelectorAll(\'h1\').length) {\n    require.ensure([], function () {\n        var Header = require(\'./Components/Header\').default;\n        new Header().render(\'h1\');\n    });\n}',
            _name: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/babel-loader/lib/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/src/index.js' },
         assets: {},
         built: true,
         _cachedSource: null,
         issuer: null,
         building: undefined,
         buildTimestamp: 1487145343426,
         cacheable: true },
       [length]: 1 ],
    entrypoints: 
     [ Entrypoint { name: 'main', chunks: [ [Circular], [length]: 1 ] },
       [length]: 1 ],
    chunks: 
     [ Chunk {
         id: null,
         ids: null,
         debugId: 1001,
         name: null,
         modules: 
          [ [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [length]: 8 ],
         entrypoints: [ [length]: 0 ],
         chunks: [ [length]: 0 ],
         parents: [ [Circular], [length]: 1 ],
         blocks: [ [Object], [length]: 1 ],
         origins: [ [Object], [length]: 1 ],
         files: [ [length]: 0 ],
         rendered: false,
         _removeAndDo: 
          { [Function: removeAndDo]
            [length]: 3,
            [name]: 'removeAndDo',
            [arguments]: null,
            [caller]: null,
            [prototype]: [Object] },
         addChunk: { [Function: createAdderCallback] [length]: 1, [name]: 'createAdderCallback' },
         addParent: { [Function: createAdderCallback] [length]: 1, [name]: 'createAdderCallback' } },
       Chunk {
         id: null,
         ids: null,
         debugId: 1002,
         name: null,
         modules: 
          [ [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [length]: 8 ],
         entrypoints: [ [length]: 0 ],
         chunks: [ [length]: 0 ],
         parents: [ [Circular], [length]: 1 ],
         blocks: [ [Object], [length]: 1 ],
         origins: [ [Object], [length]: 1 ],
         files: [ [length]: 0 ],
         rendered: false,
         _removeAndDo: 
          { [Function: removeAndDo]
            [length]: 3,
            [name]: 'removeAndDo',
            [arguments]: null,
            [caller]: null,
            [prototype]: [Object] },
         addChunk: { [Function: createAdderCallback] [length]: 1, [name]: 'createAdderCallback' },
         addParent: { [Function: createAdderCallback] [length]: 1, [name]: 'createAdderCallback' } },
       [length]: 2 ],
    parents: [ [length]: 0 ],
    blocks: [ [length]: 0 ],
    origins: 
     [ { module: 
          NormalModule {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            context: '/Users/klfang/Desktop/webpack-chunkfilename/src',
            reasons: [Object],
            debugId: 1000,
            lastId: null,
            id: null,
            portableId: null,
            index: 0,
            index2: 12,
            depth: 0,
            used: true,
            usedExports: true,
            providedExports: true,
            chunks: [Object],
            warnings: [Object],
            dependenciesWarnings: [Object],
            errors: [Object],
            dependenciesErrors: [Object],
            strict: true,
            meta: {},
            request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/babel-loader/lib/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
            userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
            rawRequest: './src/index.js',
            parser: [Object],
            resource: '/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
            loaders: [Object],
            fileDependencies: [Object],
            contextDependencies: [Object],
            error: null,
            _source: [Object],
            assets: {},
            built: true,
            _cachedSource: null,
            issuer: null,
            building: undefined,
            buildTimestamp: 1487145343426,
            cacheable: true },
         loc: undefined,
         name: 'main' },
       [length]: 1 ],
    files: [ [length]: 0 ],
    rendered: false,
    _removeAndDo: 
     { [Function: removeAndDo]
       [length]: 3,
       [name]: 'removeAndDo',
       [arguments]: null,
       [caller]: null,
       [prototype]: removeAndDo { [constructor]: [Circular] } },
    addChunk: { [Function: createAdderCallback] [length]: 1, [name]: 'createAdderCallback' },
    addParent: { [Function: createAdderCallback] [length]: 1, [name]: 'createAdderCallback' },
    entryModule: 
     NormalModule {
       dependencies: 
        [ ConstDependency { module: null, expression: '', range: [Object], loc: [Object] },
          [length]: 1 ],
       blocks: 
        [ RequireEnsureDependenciesBlock {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            chunkName: null,
            chunks: [Object],
            module: [Circular],
            loc: [Object],
            expr: [Object],
            range: [Object],
            chunkNameRange: null,
            parent: [Circular] },
          RequireEnsureDependenciesBlock {
            dependencies: [Object],
            blocks: [Object],
            variables: [Object],
            chunkName: null,
            chunks: [Object],
            module: [Circular],
            loc: [Object],
            expr: [Object],
            range: [Object],
            chunkNameRange: null,
            parent: [Circular] },
          [length]: 2 ],
       variables: [ [length]: 0 ],
       context: '/Users/klfang/Desktop/webpack-chunkfilename/src',
       reasons: [ [length]: 0 ],
       debugId: 1000,
       lastId: null,
       id: null,
       portableId: null,
       index: 0,
       index2: 12,
       depth: 0,
       used: true,
       usedExports: true,
       providedExports: true,
       chunks: [ [Circular], [length]: 1 ],
       warnings: 
        [ { ModuleWarning: 
          /Users/klfang/Desktop/webpack-chunkfilename/src/index.js
            15:31  warning  Strings must use doublequote  quotes
            17:32  warning  Strings must use doublequote  quotes
            18:35  warning  Strings must use doublequote  quotes
            19:23  warning  Strings must use doublequote  quotes
            23:31  warning  Strings must use doublequote  quotes
            25:32  warning  Strings must use doublequote  quotes
            26:29  warning  Strings must use doublequote  quotes
          
          ✖ 7 problems (0 errors, 7 warnings)
          
              at emitWarning (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/webpack/lib/NormalModule.js:88:25)
              at lint (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js:113:9)
              at Object.module.exports (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js:181:3)
              at LOADER_EXECUTION (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
              at runSyncOrAsync (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
              at iterateNormalLoaders (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
              at Array.<anonymous> (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
              at Storage.finished (/Users/klfang/Desktop/webpack-chunkfilename/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
              at /Users/klfang/Desktop/webpack-chunkfilename/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9
              at /Users/klfang/Desktop/webpack-chunkfilename/node_modules/graceful-fs/graceful-fs.js:78:16
              at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
            [stack]: [Getter/Setter],
            name: 'ModuleWarning',
            module: [Circular],
            message: '\n\u001b[4m/Users/klfang/Desktop/webpack-chunkfilename/src/index.js\u001b[24m\n  \u001b[2m15:31\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m17:32\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m18:35\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m19:23\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m23:31\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m25:32\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m26:29\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n\n\u001b[33m\u001b[1m✖ 7 problems (0 errors, 7 warnings)\n\u001b[22m\u001b[39m',
            warning: '\n\u001b[4m/Users/klfang/Desktop/webpack-chunkfilename/src/index.js\u001b[24m\n  \u001b[2m15:31\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m17:32\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m18:35\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m19:23\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m23:31\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m25:32\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n  \u001b[2m26:29\u001b[22m  \u001b[33mwarning\u001b[39m  Strings must use doublequote  \u001b[2mquotes\u001b[22m\n\n\u001b[33m\u001b[1m✖ 7 problems (0 errors, 7 warnings)\n\u001b[22m\u001b[39m',
            origin: null,
            dependencies: null },
          [length]: 1 ],
       dependenciesWarnings: [ [length]: 0 ],
       errors: [ [length]: 0 ],
       dependenciesErrors: [ [length]: 0 ],
       strict: true,
       meta: {},
       request: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/babel-loader/lib/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
       userRequest: '/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
       rawRequest: './src/index.js',
       parser: 
        Parser {
          _plugins: 
           { 'evaluate Literal': [Object],
             'evaluate LogicalExpression': [Object],
             'evaluate BinaryExpression': [Object],
             'evaluate UnaryExpression': [Object],
             'evaluate typeof undefined': [Object],
             'evaluate Identifier': [Object],
             'evaluate MemberExpression': [Object],
             'evaluate CallExpression': [Object],
             'evaluate CallExpression .replace': [Object],
             'evaluate CallExpression .substr': [Object],
             'evaluate TemplateLiteral': [Object],
             'evaluate TaggedTemplateExpression': [Object],
             'evaluate CallExpression .substring': [Object],
             'evaluate CallExpression .split': [Object],
             'evaluate ConditionalExpression': [Object],
             'evaluate ArrayExpression': [Object],
             'expression global': [Object],
             'expression process': [Object],
             'expression Buffer': [Object],
             'expression setImmediate': [Object],
             'expression clearImmediate': [Object],
             'call require': [Object],
             program: [Object],
             'evaluate typeof define': [Object],
             'typeof define': [Object],
             'evaluate define': [Object],
             'expression define': [Object],
             'call define': [Object],
             'evaluate typeof exports': [Object],
             'typeof exports': [Object],
             'evaluate exports': [Object],
             'expression exports': [Object],
             'call exports': [Object],
             import: [Object],
             'import specifier': [Object],
             'expression imported var': [Object],
             'expression imported var.*': [Object],
             'call imported var': [Object],
             'hot accept callback': [Object],
             'hot accept without callback': [Object],
             export: [Object],
             'export import': [Object],
             'export expression': [Object],
             'export declaration': [Object],
             'export specifier': [Object],
             'export import specifier': [Object],
             'call require:amd:array': [Object],
             'call require:amd:item': [Object],
             'call require:amd:context': [Object],
             'call define:amd:array': [Object],
             'call define:amd:item': [Object],
             'call define:amd:context': [Object],
             'expression require.amd': [Object],
             'expression define.amd': [Object],
             'expression __webpack_amd_options__': [Object],
             'evaluate typeof define.amd': [Object],
             'evaluate typeof require.amd': [Object],
             'evaluate Identifier define.amd': [Object],
             'evaluate Identifier require.amd': [Object],
             'can-rename define': [Object],
             'rename define': [Object],
             'typeof require': [Object],
             'evaluate typeof require': [Object],
             'typeof require.resolve': [Object],
             'evaluate typeof require.resolve': [Object],
             'typeof require.resolveWeak': [Object],
             'evaluate typeof require.resolveWeak': [Object],
             'evaluate typeof module': [Object],
             'assign require': [Object],
             'can-rename require': [Object],
             'rename require': [Object],
             'typeof module': [Object],
             'expression require.cache': [Object],
             'expression require': [Object],
             'call require:commonjs:item': [Object],
             'call require:commonjs:context': [Object],
             'call require.resolve': [Object],
             'call require.resolveWeak': [Object],
             'call require.resolve(Weak)': [Object],
             'call require.resolve(Weak):item': [Object],
             'call require.resolve(Weak):context': [Object],
             'expression __filename': [Object],
             'evaluate Identifier __filename': [Object],
             'expression __dirname': [Object],
             'evaluate Identifier __dirname': [Object],
             'expression require.main': [Object],
             'expression require.extensions': [Object],
             'expression module.loaded': [Object],
             'expression module.id': [Object],
             'expression module.exports': [Object],
             'evaluate Identifier module.hot': [Object],
             'expression module': [Object],
             'call require.config': [Object],
             'call requirejs.config': [Object],
             'expression require.version': [Object],
             'expression requirejs.onError': [Object],
             'expression __webpack_require__': [Object],
             'evaluate typeof __webpack_require__': [Object],
             'expression __webpack_public_path__': [Object],
             'evaluate typeof __webpack_public_path__': [Object],
             'expression __webpack_modules__': [Object],
             'evaluate typeof __webpack_modules__': [Object],
             'expression __webpack_chunk_load__': [Object],
             'evaluate typeof __webpack_chunk_load__': [Object],
             'expression __non_webpack_require__': [Object],
             'evaluate typeof __non_webpack_require__': [Object],
             'expression __webpack_nonce__': [Object],
             'evaluate typeof __webpack_nonce__': [Object],
             'expression require.onError': [Object],
             'evaluate typeof require.onError': [Object],
             'statement if': [Object],
             'expression ?:': [Object],
             'evaluate Identifier __resourceQuery': [Object],
             'expression __resourceQuery': [Object],
             'call require.include': [Object],
             'evaluate typeof require.include': [Object],
             'typeof require.include': [Object],
             'call require.ensure': [Object],
             'evaluate typeof require.ensure': [Object],
             'typeof require.ensure': [Object],
             'call require.context': [Object],
             'call System.import': [Object],
             'import-call': [Object],
             'typeof System': [Object],
             'evaluate typeof System': [Object],
             'typeof System.import': [Object],
             'evaluate typeof System.import': [Object],
             'evaluate typeof System.set': [Object],
             'expression System.set': [Object],
             'evaluate typeof System.get': [Object],
             'expression System.get': [Object],
             'evaluate typeof System.register': [Object],
             'expression System.register': [Object],
             'expression System': [Object] },
          options: undefined,
          scope: undefined,
          state: undefined },
       resource: '/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
       loaders: 
        [ { loader: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/babel-loader/lib/index.js' },
          { loader: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js' },
          [length]: 2 ],
       fileDependencies: 
        [ '/Users/klfang/Desktop/webpack-chunkfilename/src/index.js',
          [length]: 1 ],
       contextDependencies: [ [length]: 0 ],
       error: null,
       _source: 
        OriginalSource {
          _value: '\'use strict\';\n\n// var $ = require(\'jquery\');\n\n// $(\'body\').html(\'Hello\');\n\n\n// import $ from \'jquery\';\n// $(\'body\').html(\'Hello\');\n\n\n// import Button from \'./Components/Button\';\n// const button = new Button(\'google.com\');\n//  button.render(\'a\');\n\n//code splitting\nif (document.querySelectorAll(\'a\').length) {\n    require.ensure([], function () {\n        var Button = require(\'./Components/Button\').default;\n        var button = new Button(\'google.com\');\n        button.render(\'a\');\n    });\n}\n\nif (document.querySelectorAll(\'h1\').length) {\n    require.ensure([], function () {\n        var Header = require(\'./Components/Header\').default;\n        new Header().render(\'h1\');\n    });\n}',
          _name: '/Users/klfang/Desktop/webpack-chunkfilename/node_modules/babel-loader/lib/index.js!/Users/klfang/Desktop/webpack-chunkfilename/node_modules/eslint-loader/index.js!/Users/klfang/Desktop/webpack-chunkfilename/src/index.js' },
       assets: {},
       built: true,
       _cachedSource: null,
       issuer: null,
       building: undefined,
       buildTimestamp: 1487145343426,
       cacheable: true },
    filenameTemplate: '[name].bundle.js' },